name: CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
        tool:
          - cargo-hack,cargo-llvm-cov,cargo-minimal-versions,parse-changelog,cross,shellcheck,shfmt
          - cargo-hack@0.5.9,cargo-llvm-cov@0.1.13,cargo-minimal-versions@0.1.0,parse-changelog@0.4.5,cross@0.2.1,shellcheck@0.8.0,shfmt@3.4.2
        include:
          - os: macos-10.15
            tool: cargo-hack@0.5.9,cargo-llvm-cov@0.1.13,cargo-minimal-versions@0.1.0,parse-changelog@0.4.5,cross@0.2.1,shellcheck@0.8.0,shfmt@3.4.2
          - os: windows-2019
            tool: cargo-hack,cargo-llvm-cov,cargo-minimal-versions,parse-changelog
          - os: windows-2019
            tool: cargo-hack@0.5.9,cargo-llvm-cov@0.1.13,cargo-minimal-versions@0.1.0,parse-changelog@0.4.5,cross@0.2.1
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: ./
        with:
          tool: ${{ matrix.tool }}

  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/github-actions/install@main
        with:
          tool: prettier,shellcheck,shfmt
      - run: shfmt -d $(git ls-files '*.sh')
        if: always()
      - run: npx prettier -c $(git ls-files '*.yml')
        if: always()
      - run: npx prettier -c $(git ls-files '*.js')
        if: always()
      - run: shellcheck $(git ls-files '*.sh')
        if: always()
